name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Requirements
        run: |
          sudo apt update
          sudo apt install doxygen libhidapi-dev
        shell: bash

      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DENABLE_DOCS=1

      - name: Build docs
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --target docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{github.workspace}}/build/docs/html