name: Ubuntu

on:
  push:
    branches:
      - master
      - release/*
    paths-ignore:
      - docs/*
      - README.md

  pull_request:
    paths-ignore:
      - docs/*
      - README.md

defaults:
  run:
    shell: bash

jobs:
  gcc_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install gcc 10
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10

      - name: Install dependencies
        run: |
          sudo apt install libhidapi-dev libssl-dev

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release
        env:
          CC:   gcc-10
          CXX:  g++-10

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release
